version: 0.2


phases:
  install:
    runtime-version:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install --frozen-lockfile
  build:
    commands:
      - echo "Building Next.js application..."
      - npm run build
      - mkdir -pv deployment/scripts
      - cp -r .next public package.json package-lock.json appspec.yml deployment/
      - cp -r codedeploy-scripts/* deployment/scripts/
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'
  base-directory: deployment
