version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install --frozen-lockfile
  build:
    commands:
      - echo "Linting the application..."
      - npm run lint
      - echo "Unit Test for Next.js application..."
      - npm run test
  post_build:
    commands:
      - echo "Test completed on `date`"
