version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install --frozen-lockfile
  build:
    commands:
      - echo "Building Next.js application..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed on `date`"