version: 0.2


phases:
  install:
    runtime-version:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install --frozen-lockfile
  build:
    commands:
      - echo "Linting Next.js application..."
      - npm run lint
      - echo "Building Next.js application..."
      - npm run build
      - echo "Prepare artifact"
      - mkdir -pv deployment/scripts
      - cp -r .next public package.json package-lock.json deployment/
      - echo "Include CodeDeploy script to the deployment"
      - cp .aws/codedeploy-scripts/appspec.yml deployment/
      - cp -r .aws/codedeploy-scripts/* deployment/scripts/
  post_build:
    commands:
      - echo "Build completed on `date`"
artifacts:
  files:
    - '**/*'
  base-directory: deployment
